home/urls.py
from django.urls import path
from . import views

# urls.py は、Django アプリケーションの URL ルーティングを定義するファイルです。

# app_name は、URL 名前空間を定義するための変数です。
app_name = "home"

urlpatterns = [    
    path("", views.IndexView.as_view(), name="index"),
    path("<int:pk>/", views.DetailView.as_view(), name="detail"),
    path("<int:pk>/results/", views.ResultsView.as_view(), name="results"),
    path("<int:question_id>/vote/", views.vote, name="vote"),
]

shindjango/urls.py
from django.contrib import admin
from django.urls import include, path

# urls.py は、Django プロジェクトの URL ルーティングを定義するファイルです。

urlpatterns = [
    path("home/", include("home.urls")),
    path("admin/", admin.site.urls),
]

home/models.py
import datetime

from django.db import models
from django.utils import timezone

from django.contrib import admin

# models.py は、Django アプリケーションのデータモデルを定義するファイルです。
# Django では、ORM（Object-Relational Mapping）を使用してデータベースとやり取りします。
# これにより、Python のクラスを使用してデータベースのテーブルを定義し、データを操作することができます。

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField("date published")
    
    def __str__(self):
        return self.question_text

    @admin.display(
        boolean=True,
        ordering="pub_date",
        description="Published recently?",
    )
    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

home/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.template import loader
from .models import Question
from django.views import generic
from django.urls import reverse
from django.utils import timezone
# Create your views here.

# views.py は、Django アプリケーションのビューを定義するファイルです。
# ビューは、HTTP リクエストを受け取り、HTTP レスポンスを返す関数またはクラスです。

class IndexView(generic.ListView):
    template_name = "home/index.html"
    context_object_name = "latest_question_list"

    def get_queryset(self):
        """
        Return the last five published questions (not including those set to be
        published in the future).
        """
        return Question.objects.filter(pub_date__lte=timezone.now()).order_by("-pub_date")[
            :5
        ]


class DetailView(generic.DetailView):
    model = Question
    template_name = "home/detail.html"
    
    def get_queryset(self):
        """
        Excludes any questions that aren't published yet.
        """
        return Question.objects.filter(pub_date__lte=timezone.now()) 


class ResultsView(generic.DetailView):
    model = Question
    template_name = "home/results.html"


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST["choice"])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(
            request,
            "home/detail.html",
            {
                "question": question,
                "error_message": "You didn't select a choice.",
            },
        )
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse("home:results", args=(question.id,)))

home/templates/home/base.html
<!-- templates/base.html -->
<!DOCTYPE html>
<html lang="ja">

<head>
    <meta charset="UTF-8">
    <title>{% block title %}HOME{% endblock %}</title>
</head>

<body>
    {% block content %}
    {% endblock %}
</body>

</html>

home/templates/home/detail.html
{% extends "./base.html" %}
{% block title %}Detail | {{ block.super }}{% endblock %}
{% block content %}
<form action="{% url 'home:vote' question.id %}" method="post">
    {% csrf_token %}
    <fieldset>
        <legend>
            <h1>{{ question.question_text }}</h1>
        </legend>
        {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
        {% for choice in question.choice_set.all %}
        <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
        <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
        {% endfor %}
    </fieldset>
    <input type="submit" value="Vote">
</form>
{% endblock %}

home/templates/home/index.html
{% extends "./base.html" %}
{% block content %}
{% load static %}
<link rel="stylesheet" href="{% static 'home/style.css' %}">
{% if latest_question_list %}
<ul>
    {% for question in latest_question_list %}
    <li><a href="{% url 'home:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
</ul>

{% else %}
<p>No polls are available.</p>
{% endif %}
{% endblock %}

home/templates/home/results.html
{% extends "./base.html" %}
{% block title %}Results | {{ block.super }}{% endblock %}
{% block content %}
<h1>{{ question.question_text }}</h1>

<ul>
    {% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
    {% endfor %}
</ul>

<a href="{% url 'home:detail' question.id %}">Vote again?</a>
{% endblock %}